//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransmissionRemoteDotnet {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OtherStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OtherStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TransmissionRemoteDotnet.OtherStrings", typeof(OtherStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bandwidth allocation.
        /// </summary>
        internal static string BandwidthAllocation {
            get {
                return ResourceManager.GetString("BandwidthAllocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broken.
        /// </summary>
        internal static string Broken {
            get {
                return ResourceManager.GetString("Broken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        internal static string Build {
            get {
                return ResourceManager.GetString("Build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byte.
        /// </summary>
        internal static string Byte {
            get {
                return ResourceManager.GetString("Byte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking.
        /// </summary>
        internal static string Checking {
            get {
                return ResourceManager.GetString("Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        internal static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected {0} torrents for recheck. It may take a long time. Are you sure?.
        /// </summary>
        internal static string ConfirmMultipleRecheck {
            get {
                return ResourceManager.GetString("ConfirmMultipleRecheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected {0} torrents for removal. Are you sure?.
        /// </summary>
        internal static string ConfirmMultipleRemove {
            get {
                return ResourceManager.GetString("ConfirmMultipleRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected {0} torrents for removal. Are you sure?{1}ALL THE DATA FROM THESE TORRENTS WILL BE REMOVED..
        /// </summary>
        internal static string ConfirmMultipleRemoveAndDelete {
            get {
                return ResourceManager.GetString("ConfirmMultipleRemoveAndDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; server settings have been changed. Would you like to save it?.
        /// </summary>
        internal static string ConfirmSaveServer {
            get {
                return ResourceManager.GetString("ConfirmSaveServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to recheck {0}? It may take a long time..
        /// </summary>
        internal static string ConfirmSingleRecheck {
            get {
                return ResourceManager.GetString("ConfirmSingleRecheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove {0}?.
        /// </summary>
        internal static string ConfirmSingleRemove {
            get {
                return ResourceManager.GetString("ConfirmSingleRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove and delete {0}?{1}ALL THE DATA FROM THIS TORRENT WILL BE REMOVED..
        /// </summary>
        internal static string ConfirmSingleRemoveAndDelete {
            get {
                return ResourceManager.GetString("ConfirmSingleRemoveAndDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected. Getting torrent information....
        /// </summary>
        internal static string ConnectedGettingInfo {
            get {
                return ResourceManager.GetString("ConnectedGettingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to.
        /// </summary>
        internal static string ConnectedTo {
            get {
                return ResourceManager.GetString("ConnectedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting.
        /// </summary>
        internal static string Connecting {
            get {
                return ResourceManager.GetString("Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV info to clipboard.
        /// </summary>
        internal static string CopyAsCSV {
            get {
                return ResourceManager.GetString("CopyAsCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        internal static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected. Exceeded maximum number of failed requests..
        /// </summary>
        internal static string DisconnectedExceeded {
            get {
                return ResourceManager.GetString("DisconnectedExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display statistics.
        /// </summary>
        internal static string DisplayStatistics {
            get {
                return ResourceManager.GetString("DisplayStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        internal static string Down {
            get {
                return ResourceManager.GetString("Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1} valid).
        /// </summary>
        internal static string DownloadedValid {
            get {
                return ResourceManager.GetString("DownloadedValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        internal static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Limit.
        /// </summary>
        internal static string DownloadLimit {
            get {
                return ResourceManager.GetString("DownloadLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty file.
        /// </summary>
        internal static string EmptyFile {
            get {
                return ResourceManager.GetString("EmptyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed request.
        /// </summary>
        internal static string FailedRequest {
            get {
                return ResourceManager.GetString("FailedRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed exists.
        /// </summary>
        internal static string FeedExists {
            get {
                return ResourceManager.GetString("FeedExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeoIP init error ({0}).
        /// </summary>
        internal static string GeoipInitError {
            get {
                return ResourceManager.GetString("GeoipInitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gigabyte.
        /// </summary>
        internal static string Gigabyte {
            get {
                return ResourceManager.GetString("Gigabyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        internal static string GigabyteShort {
            get {
                return ResourceManager.GetString("GigabyteShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High priority.
        /// </summary>
        internal static string HighPriority {
            get {
                return ResourceManager.GetString("HighPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        internal static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        internal static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daemon try to download something, but the http result is:{0}{1}.
        /// </summary>
        internal static string HttpError {
            get {
                return ResourceManager.GetString("HttpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete.
        /// </summary>
        internal static string Incomplete {
            get {
                return ResourceManager.GetString("Incomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info object to clipboard.
        /// </summary>
        internal static string InfoObjectToClipboard {
            get {
                return ResourceManager.GetString("InfoObjectToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input accepted.
        /// </summary>
        internal static string InputAccepted {
            get {
                return ResourceManager.GetString("InputAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid RPC location.
        /// </summary>
        internal static string InvalidRPCLocation {
            get {
                return ResourceManager.GetString("InvalidRPCLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilobyte.
        /// </summary>
        internal static string Kilobyte {
            get {
                return ResourceManager.GetString("Kilobyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KB.
        /// </summary>
        internal static string KilobyteShort {
            get {
                return ResourceManager.GetString("KilobyteShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are using the latest version ({0}.{1})..
        /// </summary>
        internal static string LatestVersion {
            get {
                return ResourceManager.GetString("LatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest version check failed.
        /// </summary>
        internal static string LatestVersionCheckFailed {
            get {
                return ResourceManager.GetString("LatestVersionCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading {0}....
        /// </summary>
        internal static string LoadingFile {
            get {
                return ResourceManager.GetString("LoadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low priority.
        /// </summary>
        internal static string LowPriority {
            get {
                return ResourceManager.GetString("LowPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample mapping:.
        /// </summary>
        internal static string MappingSample {
            get {
                return ResourceManager.GetString("MappingSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megabyte.
        /// </summary>
        internal static string Megabyte {
            get {
                return ResourceManager.GetString("Megabyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        internal static string MegabyteShort {
            get {
                return ResourceManager.GetString("MegabyteShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        internal static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move multiple torrent data.
        /// </summary>
        internal static string MoveMultipleTorrents {
            get {
                return ResourceManager.GetString("MoveMultipleTorrents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move torrent data.
        /// </summary>
        internal static string MoveTorrentData {
            get {
                return ResourceManager.GetString("MoveTorrentData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move {0}.
        /// </summary>
        internal static string MoveX {
            get {
                return ResourceManager.GetString("MoveX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Torrent Properties.
        /// </summary>
        internal static string MultipleTorrentProperties {
            get {
                return ResourceManager.GetString("MultipleTorrentProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be connected to add torrents. Would you like to connect now?.
        /// </summary>
        internal static string MustBeConnected {
            get {
                return ResourceManager.GetString("MustBeConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a newer version ({0}.{1}) available. Would you like to visit the downloads page?.
        /// </summary>
        internal static string NewerVersion {
            get {
                return ResourceManager.GetString("NewerVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New torrent {0}..
        /// </summary>
        internal static string NewTorrentIs {
            get {
                return ResourceManager.GetString("NewTorrentIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hostname has been set..
        /// </summary>
        internal static string NoHostnameSet {
            get {
                return ResourceManager.GetString("NoHostnameSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal priority.
        /// </summary>
        internal static string NormalPriority {
            get {
                return ResourceManager.GetString("NormalPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected.
        /// </summary>
        internal static string NotConnected {
            get {
                return ResourceManager.GetString("NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No upgrade available.
        /// </summary>
        internal static string NoUpgradeAvailable {
            get {
                return ResourceManager.GetString("NoUpgradeAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BitTorrent Metafile (*.torrent)|*.torrent|All Files (*.*)|*.*.
        /// </summary>
        internal static string OpenFileFilter {
            get {
                return ResourceManager.GetString("OpenFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG Image|*.png.
        /// </summary>
        internal static string OpenImageFilter {
            get {
                return ResourceManager.GetString("OpenImageFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open on Network Share.
        /// </summary>
        internal static string OpenNetworkShare {
            get {
                return ResourceManager.GetString("OpenNetworkShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause all.
        /// </summary>
        internal static string PauseAll {
            get {
                return ResourceManager.GetString("PauseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        internal static string Paused {
            get {
                return ResourceManager.GetString("Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pieces.
        /// </summary>
        internal static string Pieces {
            get {
                return ResourceManager.GetString("Pieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} x {1} (have {2}).
        /// </summary>
        internal static string PiecesInfo {
            get {
                return ResourceManager.GetString("PiecesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The incoming port on your daemon is CLOSED..
        /// </summary>
        internal static string PortIsClosed {
            get {
                return ResourceManager.GetString("PortIsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The incoming port on your daemon is OPEN..
        /// </summary>
        internal static string PortIsOpen {
            get {
                return ResourceManager.GetString("PortIsOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port test result.
        /// </summary>
        internal static string PortTestResult {
            get {
                return ResourceManager.GetString("PortTestResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        internal static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Querying....
        /// </summary>
        internal static string Querying {
            get {
                return ResourceManager.GetString("Querying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reannounce.
        /// </summary>
        internal static string Reannounce {
            get {
                return ResourceManager.GetString("Reannounce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recheck.
        /// </summary>
        internal static string Recheck {
            get {
                return ResourceManager.GetString("Recheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove and delete.
        /// </summary>
        internal static string RemoveAndDelete {
            get {
                return ResourceManager.GetString("RemoveAndDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision.
        /// </summary>
        internal static string Revision {
            get {
                return ResourceManager.GetString("Revision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RpcVersion.
        /// </summary>
        internal static string RpcVersion {
            get {
                return ResourceManager.GetString("RpcVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RpcVersionMinimum.
        /// </summary>
        internal static string RpcVersionMinimum {
            get {
                return ResourceManager.GetString("RpcVersionMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samba share:.
        /// </summary>
        internal static string SambaShare {
            get {
                return ResourceManager.GetString("SambaShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second.
        /// </summary>
        internal static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seeding.
        /// </summary>
        internal static string Seeding {
            get {
                return ResourceManager.GetString("Seeding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        internal static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 sec|10 sec|30 sec|5 min.
        /// </summary>
        internal static string SpeedResolutions {
            get {
                return ResourceManager.GetString("SpeedResolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start all.
        /// </summary>
        internal static string StartAll {
            get {
                return ResourceManager.GetString("StartAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TB.
        /// </summary>
        internal static string TerabyteShort {
            get {
                return ResourceManager.GetString("TerabyteShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This torrent is now complete.
        /// </summary>
        internal static string TheTorrentHasFinishedDownloading {
            get {
                return ResourceManager.GetString("TheTorrentHasFinishedDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This torrent has finished downloading..
        /// </summary>
        internal static string TorrentFinished {
            get {
                return ResourceManager.GetString("TorrentFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torrents.
        /// </summary>
        internal static string Torrents {
            get {
                return ResourceManager.GetString("Torrents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1} done) ({2} valid).
        /// </summary>
        internal static string TotalDoneValidSize {
            get {
                return ResourceManager.GetString("TotalDoneValidSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1} done) ({2} valid) ({3} total).
        /// </summary>
        internal static string TotalDoneValidTotalSize {
            get {
                return ResourceManager.GetString("TotalDoneValidTotalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open.
        /// </summary>
        internal static string UnableToOpen {
            get {
                return ResourceManager.GetString("UnableToOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse the server response.
        /// </summary>
        internal static string UnableToParse {
            get {
                return ResourceManager.GetString("UnableToParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byte|Kilobyte|Metabyte|Gigabyte|Terabyte.
        /// </summary>
        internal static string UnitFactors {
            get {
                return ResourceManager.GetString("UnitFactors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unix path exists.
        /// </summary>
        internal static string UnixPathExists {
            get {
                return ResourceManager.GetString("UnixPathExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNIX path prefix:.
        /// </summary>
        internal static string UnixPathPrefix {
            get {
                return ResourceManager.GetString("UnixPathPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown (negative).
        /// </summary>
        internal static string UnknownNegativeResult {
            get {
                return ResourceManager.GetString("UnknownNegativeResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown response tag.
        /// </summary>
        internal static string UnknownResponseTag {
            get {
                return ResourceManager.GetString("UnknownResponseTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlimited.
        /// </summary>
        internal static string Unlimited {
            get {
                return ResourceManager.GetString("Unlimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuccessful request.
        /// </summary>
        internal static string UnsuccessfulRequest {
            get {
                return ResourceManager.GetString("UnsuccessfulRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        internal static string Up {
            get {
                return ResourceManager.GetString("Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating....
        /// </summary>
        internal static string Updating {
            get {
                return ResourceManager.GetString("Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade available.
        /// </summary>
        internal static string UpgradeAvailable {
            get {
                return ResourceManager.GetString("UpgradeAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Limit.
        /// </summary>
        internal static string UploadLimit {
            get {
                return ResourceManager.GetString("UploadLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for input.
        /// </summary>
        internal static string WaitingForInput {
            get {
                return ResourceManager.GetString("WaitingForInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting to check.
        /// </summary>
        internal static string WaitingToCheck {
            get {
                return ResourceManager.GetString("WaitingToCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} connected.
        /// </summary>
        internal static string XConnected {
            get {
                return ResourceManager.GetString("XConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} in blocklist..
        /// </summary>
        internal static string XInBlocklist {
            get {
                return ResourceManager.GetString("XInBlocklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} connected.
        /// </summary>
        internal static string XOfYConnected {
            get {
                return ResourceManager.GetString("XOfYConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
