// transmission-remote-dotnet
// http://code.google.com/p/transmission-remote-dotnet/
// Copyright (C) 2009 Alan F
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransmissionRemoteDotnet.Properties {
    using System;
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Flags {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Flags() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TransmissionRemoteDotnet.Properties.Flags", typeof(Flags).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        public static System.Drawing.Bitmap GetFlags(string name)
        {
            object obj = ResourceManager.GetObject(name, resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }

        internal static System.Drawing.Bitmap flags_ad {
            get {
                object obj = ResourceManager.GetObject("flags_ad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_ae {
            get {
                object obj = ResourceManager.GetObject("flags_ae", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_af {
            get {
                object obj = ResourceManager.GetObject("flags_af", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_ag {
            get {
                object obj = ResourceManager.GetObject("flags_ag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_ai {
            get {
                object obj = ResourceManager.GetObject("flags_ai", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_al {
            get {
                object obj = ResourceManager.GetObject("flags_al", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_am {
            get {
                object obj = ResourceManager.GetObject("flags_am", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_an {
            get {
                object obj = ResourceManager.GetObject("flags_an", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_ao {
            get {
                object obj = ResourceManager.GetObject("flags_ao", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_aq {
            get {
                object obj = ResourceManager.GetObject("flags_aq", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_ar {
            get {
                object obj = ResourceManager.GetObject("flags_ar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_as {
            get {
                object obj = ResourceManager.GetObject("flags_as", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_at {
            get {
                object obj = ResourceManager.GetObject("flags_at", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_au {
            get {
                object obj = ResourceManager.GetObject("flags_au", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_aw {
            get {
                object obj = ResourceManager.GetObject("flags_aw", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_ax {
            get {
                object obj = ResourceManager.GetObject("flags_ax", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_az {
            get {
                object obj = ResourceManager.GetObject("flags_az", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_ba {
            get {
                object obj = ResourceManager.GetObject("flags_ba", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_bb {
            get {
                object obj = ResourceManager.GetObject("flags_bb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_bd {
            get {
                object obj = ResourceManager.GetObject("flags_bd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_be {
            get {
                object obj = ResourceManager.GetObject("flags_be", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_bf {
            get {
                object obj = ResourceManager.GetObject("flags_bf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_bg {
            get {
                object obj = ResourceManager.GetObject("flags_bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_bh {
            get {
                object obj = ResourceManager.GetObject("flags_bh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_bi {
            get {
                object obj = ResourceManager.GetObject("flags_bi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_bj {
            get {
                object obj = ResourceManager.GetObject("flags_bj", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_bm {
            get {
                object obj = ResourceManager.GetObject("flags_bm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_bn {
            get {
                object obj = ResourceManager.GetObject("flags_bn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_bo {
            get {
                object obj = ResourceManager.GetObject("flags_bo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_br {
            get {
                object obj = ResourceManager.GetObject("flags_br", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_bs {
            get {
                object obj = ResourceManager.GetObject("flags_bs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_bt {
            get {
                object obj = ResourceManager.GetObject("flags_bt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_bv {
            get {
                object obj = ResourceManager.GetObject("flags_bv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_bw {
            get {
                object obj = ResourceManager.GetObject("flags_bw", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_by {
            get {
                object obj = ResourceManager.GetObject("flags_by", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_bz {
            get {
                object obj = ResourceManager.GetObject("flags_bz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_ca {
            get {
                object obj = ResourceManager.GetObject("flags_ca", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_cd {
            get {
                object obj = ResourceManager.GetObject("flags_cd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_cf {
            get {
                object obj = ResourceManager.GetObject("flags_cf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_cg {
            get {
                object obj = ResourceManager.GetObject("flags_cg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_ch {
            get {
                object obj = ResourceManager.GetObject("flags_ch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_ci {
            get {
                object obj = ResourceManager.GetObject("flags_ci", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_ck {
            get {
                object obj = ResourceManager.GetObject("flags_ck", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_cl {
            get {
                object obj = ResourceManager.GetObject("flags_cl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_cm {
            get {
                object obj = ResourceManager.GetObject("flags_cm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_cn {
            get {
                object obj = ResourceManager.GetObject("flags_cn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_co {
            get {
                object obj = ResourceManager.GetObject("flags_co", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_cr {
            get {
                object obj = ResourceManager.GetObject("flags_cr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_cs {
            get {
                object obj = ResourceManager.GetObject("flags_cs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_cu {
            get {
                object obj = ResourceManager.GetObject("flags_cu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_cv {
            get {
                object obj = ResourceManager.GetObject("flags_cv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_cy {
            get {
                object obj = ResourceManager.GetObject("flags_cy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_cz {
            get {
                object obj = ResourceManager.GetObject("flags_cz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_de {
            get {
                object obj = ResourceManager.GetObject("flags_de", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_dj {
            get {
                object obj = ResourceManager.GetObject("flags_dj", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_dk {
            get {
                object obj = ResourceManager.GetObject("flags_dk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_dm {
            get {
                object obj = ResourceManager.GetObject("flags_dm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_do {
            get {
                object obj = ResourceManager.GetObject("flags_do", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_dz {
            get {
                object obj = ResourceManager.GetObject("flags_dz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_ec {
            get {
                object obj = ResourceManager.GetObject("flags_ec", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_ee {
            get {
                object obj = ResourceManager.GetObject("flags_ee", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_eg {
            get {
                object obj = ResourceManager.GetObject("flags_eg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_er {
            get {
                object obj = ResourceManager.GetObject("flags_er", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_es {
            get {
                object obj = ResourceManager.GetObject("flags_es", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_et {
            get {
                object obj = ResourceManager.GetObject("flags_et", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_eu {
            get {
                object obj = ResourceManager.GetObject("flags_eu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_fi {
            get {
                object obj = ResourceManager.GetObject("flags_fi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_fj {
            get {
                object obj = ResourceManager.GetObject("flags_fj", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_fk {
            get {
                object obj = ResourceManager.GetObject("flags_fk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_fm {
            get {
                object obj = ResourceManager.GetObject("flags_fm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_fo {
            get {
                object obj = ResourceManager.GetObject("flags_fo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_fr {
            get {
                object obj = ResourceManager.GetObject("flags_fr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_ga {
            get {
                object obj = ResourceManager.GetObject("flags_ga", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_gb {
            get {
                object obj = ResourceManager.GetObject("flags_gb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_gd {
            get {
                object obj = ResourceManager.GetObject("flags_gd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_ge {
            get {
                object obj = ResourceManager.GetObject("flags_ge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_gf {
            get {
                object obj = ResourceManager.GetObject("flags_gf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_gh {
            get {
                object obj = ResourceManager.GetObject("flags_gh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_gi {
            get {
                object obj = ResourceManager.GetObject("flags_gi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_gl {
            get {
                object obj = ResourceManager.GetObject("flags_gl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_gm {
            get {
                object obj = ResourceManager.GetObject("flags_gm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_gn {
            get {
                object obj = ResourceManager.GetObject("flags_gn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_gp {
            get {
                object obj = ResourceManager.GetObject("flags_gp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_gq {
            get {
                object obj = ResourceManager.GetObject("flags_gq", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_gr {
            get {
                object obj = ResourceManager.GetObject("flags_gr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_gt {
            get {
                object obj = ResourceManager.GetObject("flags_gt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_gu {
            get {
                object obj = ResourceManager.GetObject("flags_gu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_gw {
            get {
                object obj = ResourceManager.GetObject("flags_gw", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_gy {
            get {
                object obj = ResourceManager.GetObject("flags_gy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_hk {
            get {
                object obj = ResourceManager.GetObject("flags_hk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_hm {
            get {
                object obj = ResourceManager.GetObject("flags_hm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_hn {
            get {
                object obj = ResourceManager.GetObject("flags_hn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_hr {
            get {
                object obj = ResourceManager.GetObject("flags_hr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_ht {
            get {
                object obj = ResourceManager.GetObject("flags_ht", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_hu {
            get {
                object obj = ResourceManager.GetObject("flags_hu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_id {
            get {
                object obj = ResourceManager.GetObject("flags_id", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_ie {
            get {
                object obj = ResourceManager.GetObject("flags_ie", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_il {
            get {
                object obj = ResourceManager.GetObject("flags_il", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_im {
            get {
                object obj = ResourceManager.GetObject("flags_im", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_in {
            get {
                object obj = ResourceManager.GetObject("flags_in", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_io {
            get {
                object obj = ResourceManager.GetObject("flags_io", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_iq {
            get {
                object obj = ResourceManager.GetObject("flags_iq", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_ir {
            get {
                object obj = ResourceManager.GetObject("flags_ir", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_is {
            get {
                object obj = ResourceManager.GetObject("flags_is", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_it {
            get {
                object obj = ResourceManager.GetObject("flags_it", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_je {
            get {
                object obj = ResourceManager.GetObject("flags_je", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_jm {
            get {
                object obj = ResourceManager.GetObject("flags_jm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_jo {
            get {
                object obj = ResourceManager.GetObject("flags_jo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_jp {
            get {
                object obj = ResourceManager.GetObject("flags_jp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_ke {
            get {
                object obj = ResourceManager.GetObject("flags_ke", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_kg {
            get {
                object obj = ResourceManager.GetObject("flags_kg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_kh {
            get {
                object obj = ResourceManager.GetObject("flags_kh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_ki {
            get {
                object obj = ResourceManager.GetObject("flags_ki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_km {
            get {
                object obj = ResourceManager.GetObject("flags_km", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_kn {
            get {
                object obj = ResourceManager.GetObject("flags_kn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_kp {
            get {
                object obj = ResourceManager.GetObject("flags_kp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_kr {
            get {
                object obj = ResourceManager.GetObject("flags_kr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_kw {
            get {
                object obj = ResourceManager.GetObject("flags_kw", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_ky {
            get {
                object obj = ResourceManager.GetObject("flags_ky", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_kz {
            get {
                object obj = ResourceManager.GetObject("flags_kz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_la {
            get {
                object obj = ResourceManager.GetObject("flags_la", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_lb {
            get {
                object obj = ResourceManager.GetObject("flags_lb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_lc {
            get {
                object obj = ResourceManager.GetObject("flags_lc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_li {
            get {
                object obj = ResourceManager.GetObject("flags_li", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_lk {
            get {
                object obj = ResourceManager.GetObject("flags_lk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_lr {
            get {
                object obj = ResourceManager.GetObject("flags_lr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_ls {
            get {
                object obj = ResourceManager.GetObject("flags_ls", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_lt {
            get {
                object obj = ResourceManager.GetObject("flags_lt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_lu {
            get {
                object obj = ResourceManager.GetObject("flags_lu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_lv {
            get {
                object obj = ResourceManager.GetObject("flags_lv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_ly {
            get {
                object obj = ResourceManager.GetObject("flags_ly", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_ma {
            get {
                object obj = ResourceManager.GetObject("flags_ma", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_mc {
            get {
                object obj = ResourceManager.GetObject("flags_mc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_md {
            get {
                object obj = ResourceManager.GetObject("flags_md", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_me {
            get {
                object obj = ResourceManager.GetObject("flags_me", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_mg {
            get {
                object obj = ResourceManager.GetObject("flags_mg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_mh {
            get {
                object obj = ResourceManager.GetObject("flags_mh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_mk {
            get {
                object obj = ResourceManager.GetObject("flags_mk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_ml {
            get {
                object obj = ResourceManager.GetObject("flags_ml", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_mm {
            get {
                object obj = ResourceManager.GetObject("flags_mm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_mn {
            get {
                object obj = ResourceManager.GetObject("flags_mn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_mo {
            get {
                object obj = ResourceManager.GetObject("flags_mo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_mp {
            get {
                object obj = ResourceManager.GetObject("flags_mp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_mq {
            get {
                object obj = ResourceManager.GetObject("flags_mq", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_mr {
            get {
                object obj = ResourceManager.GetObject("flags_mr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_ms {
            get {
                object obj = ResourceManager.GetObject("flags_ms", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_mt {
            get {
                object obj = ResourceManager.GetObject("flags_mt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_mu {
            get {
                object obj = ResourceManager.GetObject("flags_mu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_mv {
            get {
                object obj = ResourceManager.GetObject("flags_mv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_mw {
            get {
                object obj = ResourceManager.GetObject("flags_mw", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_mx {
            get {
                object obj = ResourceManager.GetObject("flags_mx", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_my {
            get {
                object obj = ResourceManager.GetObject("flags_my", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_mz {
            get {
                object obj = ResourceManager.GetObject("flags_mz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_na {
            get {
                object obj = ResourceManager.GetObject("flags_na", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_nc {
            get {
                object obj = ResourceManager.GetObject("flags_nc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_ne {
            get {
                object obj = ResourceManager.GetObject("flags_ne", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_nf {
            get {
                object obj = ResourceManager.GetObject("flags_nf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_ng {
            get {
                object obj = ResourceManager.GetObject("flags_ng", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_ni {
            get {
                object obj = ResourceManager.GetObject("flags_ni", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_nl {
            get {
                object obj = ResourceManager.GetObject("flags_nl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_no {
            get {
                object obj = ResourceManager.GetObject("flags_no", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_np {
            get {
                object obj = ResourceManager.GetObject("flags_np", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_nr {
            get {
                object obj = ResourceManager.GetObject("flags_nr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_nu {
            get {
                object obj = ResourceManager.GetObject("flags_nu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_nz {
            get {
                object obj = ResourceManager.GetObject("flags_nz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_om {
            get {
                object obj = ResourceManager.GetObject("flags_om", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_pa {
            get {
                object obj = ResourceManager.GetObject("flags_pa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_pe {
            get {
                object obj = ResourceManager.GetObject("flags_pe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_pf {
            get {
                object obj = ResourceManager.GetObject("flags_pf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_pg {
            get {
                object obj = ResourceManager.GetObject("flags_pg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_ph {
            get {
                object obj = ResourceManager.GetObject("flags_ph", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_pk {
            get {
                object obj = ResourceManager.GetObject("flags_pk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_pl {
            get {
                object obj = ResourceManager.GetObject("flags_pl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_pm {
            get {
                object obj = ResourceManager.GetObject("flags_pm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_pr {
            get {
                object obj = ResourceManager.GetObject("flags_pr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_ps {
            get {
                object obj = ResourceManager.GetObject("flags_ps", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_pt {
            get {
                object obj = ResourceManager.GetObject("flags_pt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_pw {
            get {
                object obj = ResourceManager.GetObject("flags_pw", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_py {
            get {
                object obj = ResourceManager.GetObject("flags_py", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_qa {
            get {
                object obj = ResourceManager.GetObject("flags_qa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_re {
            get {
                object obj = ResourceManager.GetObject("flags_re", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_ro {
            get {
                object obj = ResourceManager.GetObject("flags_ro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_rs {
            get {
                object obj = ResourceManager.GetObject("flags_rs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_ru {
            get {
                object obj = ResourceManager.GetObject("flags_ru", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_rw {
            get {
                object obj = ResourceManager.GetObject("flags_rw", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_sa {
            get {
                object obj = ResourceManager.GetObject("flags_sa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_sb {
            get {
                object obj = ResourceManager.GetObject("flags_sb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_sc {
            get {
                object obj = ResourceManager.GetObject("flags_sc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_sd {
            get {
                object obj = ResourceManager.GetObject("flags_sd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_se {
            get {
                object obj = ResourceManager.GetObject("flags_se", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_sg {
            get {
                object obj = ResourceManager.GetObject("flags_sg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_si {
            get {
                object obj = ResourceManager.GetObject("flags_si", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_sk {
            get {
                object obj = ResourceManager.GetObject("flags_sk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_sl {
            get {
                object obj = ResourceManager.GetObject("flags_sl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_sm {
            get {
                object obj = ResourceManager.GetObject("flags_sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_sn {
            get {
                object obj = ResourceManager.GetObject("flags_sn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_so {
            get {
                object obj = ResourceManager.GetObject("flags_so", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_sr {
            get {
                object obj = ResourceManager.GetObject("flags_sr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_st {
            get {
                object obj = ResourceManager.GetObject("flags_st", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_sv {
            get {
                object obj = ResourceManager.GetObject("flags_sv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_sy {
            get {
                object obj = ResourceManager.GetObject("flags_sy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_sz {
            get {
                object obj = ResourceManager.GetObject("flags_sz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_tc {
            get {
                object obj = ResourceManager.GetObject("flags_tc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_td {
            get {
                object obj = ResourceManager.GetObject("flags_td", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_tf {
            get {
                object obj = ResourceManager.GetObject("flags_tf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_tg {
            get {
                object obj = ResourceManager.GetObject("flags_tg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_th {
            get {
                object obj = ResourceManager.GetObject("flags_th", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_tj {
            get {
                object obj = ResourceManager.GetObject("flags_tj", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_tk {
            get {
                object obj = ResourceManager.GetObject("flags_tk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_tm {
            get {
                object obj = ResourceManager.GetObject("flags_tm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_tn {
            get {
                object obj = ResourceManager.GetObject("flags_tn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_to {
            get {
                object obj = ResourceManager.GetObject("flags_to", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_tp {
            get {
                object obj = ResourceManager.GetObject("flags_tp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_tr {
            get {
                object obj = ResourceManager.GetObject("flags_tr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_tt {
            get {
                object obj = ResourceManager.GetObject("flags_tt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_tv {
            get {
                object obj = ResourceManager.GetObject("flags_tv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_tw {
            get {
                object obj = ResourceManager.GetObject("flags_tw", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_tz {
            get {
                object obj = ResourceManager.GetObject("flags_tz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_ua {
            get {
                object obj = ResourceManager.GetObject("flags_ua", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_ug {
            get {
                object obj = ResourceManager.GetObject("flags_ug", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_uk {
            get {
                object obj = ResourceManager.GetObject("flags_uk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_um {
            get {
                object obj = ResourceManager.GetObject("flags_um", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_us {
            get {
                object obj = ResourceManager.GetObject("flags_us", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_uy {
            get {
                object obj = ResourceManager.GetObject("flags_uy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_uz {
            get {
                object obj = ResourceManager.GetObject("flags_uz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_va {
            get {
                object obj = ResourceManager.GetObject("flags_va", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_vc {
            get {
                object obj = ResourceManager.GetObject("flags_vc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_ve {
            get {
                object obj = ResourceManager.GetObject("flags_ve", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_vg {
            get {
                object obj = ResourceManager.GetObject("flags_vg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_vi {
            get {
                object obj = ResourceManager.GetObject("flags_vi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_vn {
            get {
                object obj = ResourceManager.GetObject("flags_vn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_vu {
            get {
                object obj = ResourceManager.GetObject("flags_vu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_wf {
            get {
                object obj = ResourceManager.GetObject("flags_wf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_ws {
            get {
                object obj = ResourceManager.GetObject("flags_ws", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_ye {
            get {
                object obj = ResourceManager.GetObject("flags_ye", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_yt {
            get {
                object obj = ResourceManager.GetObject("flags_yt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_yu {
            get {
                object obj = ResourceManager.GetObject("flags_yu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_za {
            get {
                object obj = ResourceManager.GetObject("flags_za", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_zm {
            get {
                object obj = ResourceManager.GetObject("flags_zm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_zr {
            get {
                object obj = ResourceManager.GetObject("flags_zr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flags_zw {
            get {
                object obj = ResourceManager.GetObject("flags_zw", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
